## Association Rule Mining

In [226]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [227]:
dfretail = pd.read_excel('Online_Retail.xlsx')

In [228]:
dfretail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [229]:
dfretail.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
284787,561887,21403,BLUE EGG SPOON,24,2011-07-31 13:33:00,0.12,14414.0,United Kingdom
410930,572185,35970,ZINC FOLKART SLEIGH BELLS,23,2011-10-21 10:52:00,8.33,NaN,United Kingdom
517558,580062,84012,MAGIC SHEEP WOOL GROWING FROM PAPER,2,2011-12-01 13:28:00,0.85,15862.0,United Kingdom
70241,542000,23231,WRAP DOILEY DESIGN,25,2011-01-25 10:49:00,0.42,14257.0,United Kingdom
402763,571508,22585,PACK OF 6 BIRDY GIFT TAGS,5,2011-10-17 15:27:00,2.46,NaN,United Kingdom
127432,547222,72760B,VINTAGE CREAM 3 BASKET CAKE STAND,2,2011-03-21 15:07:00,9.95,18008.0,United Kingdom
416770,572558,21507,ELEPHANT BIRTHDAY CARD,12,2011-10-25 08:26:00,0.42,14286.0,United Kingdom
101667,544928,90013A,MIDNIGHT BLUE VINTAGE EARRINGS,1,2011-02-24 18:07:00,3.73,NaN,United Kingdom
213819,555558,20724,RED RETROSPOT CHARLOTTE BAG,2,2011-06-05 14:06:00,0.85,14159.0,United Kingdom
144797,548808,72800E,4 IVORY DINNER CANDLES SILVER FLOCK,5,2011-04-04 12:55:00,2.55,17774.0,United Kingdom

In [230]:
dfretail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
InvoiceNo      541909 non-null object
StockCode      541909 non-null object
Description    540455 non-null object
Quantity       541909 non-null int64
InvoiceDate    541909 non-null datetime64[ns]
UnitPrice      541909 non-null float64
CustomerID     406829 non-null float64
Country        541909 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [231]:
dfretail.Country.unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [232]:
dfretail['Country'].value_counts()

United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: Country, dtype: int64

In [233]:
dfretail.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [234]:
dfretail['InvoiceNo']= dfretail['InvoiceNo'].astype('str')

In [235]:
 #Get the invoice numbers which doesn't contain 'C'
dfretail['InvoiceNo'] = dfretail[~dfretail['InvoiceNo'].str.contains('C')]

In [236]:
dfretail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [205]:
#deleate leading and trailing spaces
dfretail['Description'] = dfretail['Description'].str.strip()

In [206]:
dfretail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [207]:
dfretail.dropna(inplace = True)

In [208]:
dfretail['Country'].value_counts()

United Kingdom          361878
Germany                   9495
France                    8491
EIRE                      7485
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               1877
Portugal                  1480
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
USA                        291
Israel                     250
Unspecified                244
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     17
Saudi Arabia                10
Name: Country, dtype: int64

In [209]:
dfretail.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
InvoiceNo      406829 non-null object
StockCode      406829 non-null object
Description    406829 non-null object
Quantity       406829 non-null int64
InvoiceDate    406829 non-null datetime64[ns]
UnitPrice      406829 non-null float64
CustomerID     406829 non-null float64
Country        406829 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

In [210]:
#create a basket for the data belonginmg to country 'France'
basket = dfretail[dfretail['Country']=='France']

In [211]:
basket.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
14146,537463,21212,PACK OF 72 RETROSPOT CAKE CASES,24,2010-12-07 10:08:00,0.55,12681.0,France
180541,552325,22379,RECYCLING BAG RETROSPOT,10,2011-05-09 09:47:00,2.10,12490.0,France
448326,575049,22333,RETROSPOT PARTY BAG + STICKER SET,8,2011-11-08 12:13:00,1.65,12721.0,France
515915,579792,22752,SET 7 BABUSHKA NESTING BOXES,8,2011-11-30 15:43:00,8.50,12714.0,France
224153,556507,20726,LUNCH BAG WOODLAND,10,2011-06-13 09:55:00,1.65,12567.0,France
391463,570672,22400,MAGNETS PACK OF 4 HOME SWEET HOME,24,2011-10-11 14:52:00,0.39,12536.0,France
100495,544817,22714,CARD BIRTHDAY COWBOY,24,2011-02-23 16:44:00,0.42,12437.0,France
204280,554650,23209,LUNCH BAG DOILEY PATTERN,20,2011-05-25 12:54:00,1.65,12681.0,France
214915,555637,22960,JAM MAKING SET WITH JARS,6,2011-06-06 12:47:00,4.25,12535.0,France
330922,565930,22331,WOODLAND PARTY BAG + STICKER SET,8,2011-09-08 10:32:00,1.65,12685.0,France

In [212]:
#sort by InvoiceNo and Description and Get the sum of Quantity
basket = basket.groupby(['InvoiceNo','Description'])['Quantity'].sum()

In [215]:
basket

InvoiceNo  Description
536370     ALARM CLOCK BAKELIKE GREEN              12
           ALARM CLOCK BAKELIKE PINK               24
           ALARM CLOCK BAKELIKE RED                24
           CHARLOTTE BAG DOLLY GIRL DESIGN         20
           CIRCUS PARADE LUNCH BOX                 24
           INFLATABLE POLITICAL GLOBE              48
           LUNCH BOX I LOVE LONDON                 24
           MINI JIGSAW CIRCUS PARADE               24
           MINI JIGSAW SPACEBOY                    24
           MINI PAINT SET VINTAGE                  36
           PANDA AND BUNNIES STICKER SHEET         12
           POSTAGE                                  3
           RED TOADSTOOL LED NIGHT LIGHT           24
           ROUND SNACK BOXES SET OF4 WOODLAND      24
           SET 2 TEA TOWELS I LOVE LONDON          24
           SET/2 RED RETROSPOT TEA TOWELS          18
           SPACEBOY LUNCH BOX                      24
           STARS GIFT TAPE                         24
           VINTAGE HEADS AND TAILS CARD GAME       24
           VINTAGE SEASIDE JIGSAW PUZZLES          12
536852     CHARLOTTE BAG DOLLY GIRL DESIGN         10
           MINI JIGSAW DOLLY GIRL                  24
           MINI JIGSAW SPACEBOY                    24
           PICTURE DOMINOES                        12
           POLKADOT RAIN HAT                       24
           POSTAGE                                  1
           VINTAGE HEADS AND TAILS CARD GAME       12
536974     ASSORTED COLOUR MINI CASES               2
           BIG DOUGHNUT FRIDGE MAGNETS             12
           EDWARDIAN PARASOL BLACK                  9
                                                 ...
nan        REGENCY SUGAR BOWL GREEN                -1
           RETRO PLASTIC ELEPHANT TRAY            -12
           RETRO PLASTIC POLKA TRAY               -15
           RETROSPOT CHILDRENS APRON               -6
           ROUND SNACK BOXES SET OF 4 FRUITS       -6
           ROUND SNACK BOXES SET OF4 WOODLAND      -3
           RUSTIC STRAWBERRY JAM POT SMALL        -13
           SET 2 TEA TOWELS I LOVE LONDON          -6
           SET OF 3 HEART COOKIE CUTTERS          -12
           SET OF 4 KNICK KNACK TINS LEAF          -1
           SET OF 6 HALLOWEEN GHOST T-LIGHTS      -36
           SET OF 6 T-LIGHTS SANTA                -12
           SET/5 RED RETROSPOT LID GLASS BOWLS     -1
           SET/6 COLLAGE PAPER CUPS               -24
           SET/6 COLLAGE PAPER PLATES             -12
           SET/6 PINK BIRD T-LIGHT CANDLES         -3
           SILK PURSE BABUSHKA BLUE                -1
           SKULL SHOULDER BAG                     -10
           SNOWSTORM PHOTO FRAME FRIDGE MAGNET    -24
           STORAGE TIN VINTAGE DOILY               -5
           STRAWBERRY CERAMIC TRINKET BOX          -5
           TOADSTOOL BEDSIDE LIGHT                 -2
           VINTAGE BILLBOARD LOVE/HATE MUG         -5
           VINTAGE RED ENAMEL TRIM PLATE           -6
           WATERING CAN BLUE ELEPHANT              -6
           WATERING CAN PINK BUNNY                -12
           WRAP CHRISTMAS VILLAGE                -250
           WRAP GREEN PEARS                       -25
           WRAP VINTAGE PETALS  DESIGN            -25
           ZINC FOLKART SLEIGH BELLS              -36
Name: Quantity, Length: 8419, dtype: int64

In [221]:
basket = basket.unstack()

In [222]:
basket.shape

(602160,)

In [223]:
basket.head(10)

InvoiceNo  Description
536370     10 COLOUR SPACEBOY PEN                NaN
           12 COLOURED PARTY BALLOONS            NaN
           12 EGG HOUSE PAINTED WOOD             NaN
           12 MESSAGE CARDS WITH ENVELOPES       NaN
           12 PENCIL SMALL TUBE WOODLAND         NaN
           12 PENCILS SMALL TUBE RED RETROSPOT   NaN
           12 PENCILS SMALL TUBE SKULL           NaN
           12 PENCILS TALL TUBE POSY             NaN
           12 PENCILS TALL TUBE RED RETROSPOT    NaN
           12 PENCILS TALL TUBE WOODLAND         NaN
dtype: float64

In [224]:
basket = basket.fillna(0)

In [225]:
basket.head()

InvoiceNo  Description
536370     10 COLOUR SPACEBOY PEN             0.0
           12 COLOURED PARTY BALLOONS         0.0
           12 EGG HOUSE PAINTED WOOD          0.0
           12 MESSAGE CARDS WITH ENVELOPES    0.0
           12 PENCIL SMALL TUBE WOODLAND      0.0
dtype: float64

In [140]:
def encode(x):
    if x<=0:
        return 0
    else:
        return 1

In [142]:
basket_sets = basket.applymap(encode)

In [144]:
basket_sets.head(10)

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP SUKI AND FRIENDS,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537468,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537693,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537967,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
538008,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [145]:
#we can drop some items which gives very minimum profit

In [149]:
frequent_itemset = apriori(basket_sets,min_support=0.07, use_colnames=True) # 7% support

In [150]:
frequent_itemset

     support                                           itemsets
0   0.071979                      (4 TRADITIONAL SPINNING TOPS)
1   0.097686                       (ALARM CLOCK BAKELIKE GREEN)
2   0.102828                        (ALARM CLOCK BAKELIKE PINK)
3   0.095116                         (ALARM CLOCK BAKELIKE RED)
4   0.077121                     (BAKING SET 9 PIECE RETROSPOT)
5   0.071979                     (CHILDRENS CUTLERY DOLLY GIRL)
6   0.100257                             (DOLLY GIRL LUNCH BOX)
7   0.097686                          (JUMBO BAG RED RETROSPOT)
8   0.077121                       (JUMBO BAG WOODLAND ANIMALS)
9   0.125964                           (LUNCH BAG APPLE DESIGN)
10  0.084833                      (LUNCH BAG DOLLY GIRL DESIGN)
11  0.154242                          (LUNCH BAG RED RETROSPOT)
12  0.120823                        (LUNCH BAG SPACEBOY DESIGN)
13  0.118252                               (LUNCH BAG WOODLAND)
14  0.143959                 (LUNCH BOX WITH CUTLERY RETROSPOT)
15  0.105398                           (MINI PAINT SET VINTAGE)
16  0.102828                  (PACK OF 72 RETROSPOT CAKE CASES)
17  0.082262                          (PAPER BUNTING RETROSPOT)
18  0.169666                    (PLASTERS IN TIN CIRCUS PARADE)
19  0.136247                         (PLASTERS IN TIN SPACEBOY)
20  0.082262                        (PLASTERS IN TIN STRONGMAN)
21  0.172237                 (PLASTERS IN TIN WOODLAND ANIMALS)
22  0.771208                                          (POSTAGE)
23  0.187661                               (RABBIT NIGHT LIGHT)
24  0.097686                      (RED RETROSPOT CHARLOTTE BAG)
25  0.138817                         (RED RETROSPOT MINI CASES)
26  0.071979                         (RED RETROSPOT PICNIC BAG)
27  0.179949                    (RED TOADSTOOL LED NIGHT LIGHT)
28  0.125964                         (REGENCY CAKESTAND 3 TIER)
29  0.087404                  (RETROSPOT TEA SET CERAMIC 11 PC)
..       ...                                                ...
60  0.102828  (PLASTERS IN TIN CIRCUS PARADE, PLASTERS IN TI...
61  0.149100           (POSTAGE, PLASTERS IN TIN CIRCUS PARADE)
62  0.105398  (PLASTERS IN TIN SPACEBOY, PLASTERS IN TIN WOO...
63  0.115681                (POSTAGE, PLASTERS IN TIN SPACEBOY)
64  0.138817        (POSTAGE, PLASTERS IN TIN WOODLAND ANIMALS)
65  0.167095                      (POSTAGE, RABBIT NIGHT LIGHT)
66  0.082262             (POSTAGE, RED RETROSPOT CHARLOTTE BAG)
67  0.115681                (POSTAGE, RED RETROSPOT MINI CASES)
68  0.159383           (RED TOADSTOOL LED NIGHT LIGHT, POSTAGE)
69  0.105398                (POSTAGE, REGENCY CAKESTAND 3 TIER)
70  0.095116       (ROUND SNACK BOXES SET OF 4 FRUITS, POSTAGE)
71  0.149100      (POSTAGE, ROUND SNACK BOXES SET OF4 WOODLAND)
72  0.110540      (POSTAGE, SET/20 RED RETROSPOT PAPER NAPKINS)
73  0.118252             (POSTAGE, SET/6 RED SPOTTY PAPER CUPS)
74  0.107969           (POSTAGE, SET/6 RED SPOTTY PAPER PLATES)
75  0.097686                      (POSTAGE, SPACEBOY LUNCH BOX)
76  0.115681       (POSTAGE, STRAWBERRY LUNCH BOX WITH CUTLERY)
77  0.089974                 (TEA PARTY BIRTHDAY CARD, POSTAGE)
78  0.102828  (SET/6 RED SPOTTY PAPER CUPS, SET/20 RED RETRO...
79  0.102828  (SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...
80  0.123393  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...
81  0.071979  (ALARM CLOCK BAKELIKE GREEN, POSTAGE, ALARM CL...
82  0.074550  (POSTAGE, PLASTERS IN TIN CIRCUS PARADE, PLAST...
83  0.084833  (POSTAGE, PLASTERS IN TIN CIRCUS PARADE, PLAST...
84  0.084833  (POSTAGE, PLASTERS IN TIN SPACEBOY, PLASTERS I...
85  0.084833  (POSTAGE, SET/6 RED SPOTTY PAPER CUPS, SET/20 ...
86  0.084833  (POSTAGE, SET/20 RED RETROSPOT PAPER NAPKINS, ...
87  0.102828  (POSTAGE, SET/6 RED SPOTTY PAPER CUPS, SET/6 R...
88  0.100257  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...
89  0.082262  (POSTAGE, SET/6 RED SPOTTY PAPER CUPS, SET/20 ...

[90 rows x 2 columns]

In [151]:
rules = association_rules(frequent_itemset, metric='lift', min_threshold=1)

In [155]:
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.097686,0.102828,0.074550,0.763158,7.421711,0.064505,3.788061
1,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102828,0.097686,0.074550,0.725000,7.421711,0.064505,3.281140
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.097686,0.095116,0.079692,0.815789,8.576814,0.070400,4.912229
3,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.095116,0.097686,0.079692,0.837838,8.576814,0.070400,5.564267
4,(ALARM CLOCK BAKELIKE GREEN),(POSTAGE),0.097686,0.771208,0.084833,0.868421,1.126053,0.009496,1.738817
5,(POSTAGE),(ALARM CLOCK BAKELIKE GREEN),0.771208,0.097686,0.084833,0.110000,1.126053,0.009496,1.013836
6,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED),0.102828,0.095116,0.074550,0.725000,7.622297,0.064770,3.290488
7,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE PINK),0.095116,0.102828,0.074550,0.783784,7.622297,0.064770,4.149422
8,(POSTAGE),(ALARM CLOCK BAKELIKE PINK),0.771208,0.102828,0.089974,0.116667,1.134583,0.010673,1.015667
9,(ALARM CLOCK BAKELIKE PINK),(POSTAGE),0.102828,0.771208,0.089974,0.875000,1.134583,0.010673,1.830334

In [ ]:
#antecedents : LHS of Rule
#consequents: RHS of Rule

In [154]:
rules[rules['confidence']>=0.8].count()

antecedents           49
consequents           49
antecedent support    49
consequent support    49
support               49
confidence            49
lift                  49
leverage              49
conviction            49
dtype: int64

In [ ]:
#recommendation Engine